// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oauthmodule.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_StartLogoutHandler extends CustomJavaAction<Boolean>
{
	public JA_StartLogoutHandler(IContext context)
	{
		super(context);
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Core.addRequestHandler("logout/", new JA_LogoutHandler());
		Core.getLogger("OAuthSignout").info("Registered logout requesthandler for 'logout/'");		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "JA_StartLogoutHandler";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
