// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oauthmodule.proxies;

public class LogoutRedirectHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject logoutRedirectHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OauthModule.LogoutRedirectHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		URI("URI");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public LogoutRedirectHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "OauthModule.LogoutRedirectHelper"));
	}

	protected LogoutRedirectHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject logoutRedirectHelperMendixObject)
	{
		if (logoutRedirectHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("OauthModule.LogoutRedirectHelper", logoutRedirectHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a OauthModule.LogoutRedirectHelper");

		this.logoutRedirectHelperMendixObject = logoutRedirectHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'LogoutRedirectHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static oauthmodule.proxies.LogoutRedirectHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return oauthmodule.proxies.LogoutRedirectHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static oauthmodule.proxies.LogoutRedirectHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new oauthmodule.proxies.LogoutRedirectHelper(context, mendixObject);
	}

	public static oauthmodule.proxies.LogoutRedirectHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return oauthmodule.proxies.LogoutRedirectHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of URI
	 */
	public final String getURI()
	{
		return getURI(getContext());
	}

	/**
	 * @param context
	 * @return value of URI
	 */
	public final String getURI(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.URI.toString());
	}

	/**
	 * Set value of URI
	 * @param uri
	 */
	public final void setURI(String uri)
	{
		setURI(getContext(), uri);
	}

	/**
	 * Set value of URI
	 * @param context
	 * @param uri
	 */
	public final void setURI(com.mendix.systemwideinterfaces.core.IContext context, String uri)
	{
		getMendixObject().setValue(context, MemberNames.URI.toString(), uri);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return logoutRedirectHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final oauthmodule.proxies.LogoutRedirectHelper that = (oauthmodule.proxies.LogoutRedirectHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "OauthModule.LogoutRedirectHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
