// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oauthmodule.proxies;

public class OAuthConfig
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject oAuthConfigMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OauthModule.OAuthConfig";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UseGoogle("UseGoogle"),
		UserId_Google("UserId_Google"),
		UseLinkedin("UseLinkedin"),
		UserId_Linkedin("UserId_Linkedin"),
		UseFacebook("UseFacebook"),
		UserId_Facebook("UserId_Facebook"),
		OAuthConfig_Microflows("OauthModule.OAuthConfig_Microflows");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OAuthConfig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "OauthModule.OAuthConfig"));
	}

	protected OAuthConfig(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject oAuthConfigMendixObject)
	{
		if (oAuthConfigMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("OauthModule.OAuthConfig", oAuthConfigMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a OauthModule.OAuthConfig");

		this.oAuthConfigMendixObject = oAuthConfigMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'OAuthConfig.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static oauthmodule.proxies.OAuthConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return oauthmodule.proxies.OAuthConfig.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static oauthmodule.proxies.OAuthConfig initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new oauthmodule.proxies.OAuthConfig(context, mendixObject);
	}

	public static oauthmodule.proxies.OAuthConfig load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return oauthmodule.proxies.OAuthConfig.initialize(context, mendixObject);
	}

	public static java.util.List<oauthmodule.proxies.OAuthConfig> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<oauthmodule.proxies.OAuthConfig> result = new java.util.ArrayList<oauthmodule.proxies.OAuthConfig>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//OauthModule.OAuthConfig" + xpathConstraint))
			result.add(oauthmodule.proxies.OAuthConfig.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of UseGoogle
	 */
	public final Boolean getUseGoogle()
	{
		return getUseGoogle(getContext());
	}

	/**
	 * @param context
	 * @return value of UseGoogle
	 */
	public final Boolean getUseGoogle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.UseGoogle.toString());
	}

	/**
	 * Set value of UseGoogle
	 * @param usegoogle
	 */
	public final void setUseGoogle(Boolean usegoogle)
	{
		setUseGoogle(getContext(), usegoogle);
	}

	/**
	 * Set value of UseGoogle
	 * @param context
	 * @param usegoogle
	 */
	public final void setUseGoogle(com.mendix.systemwideinterfaces.core.IContext context, Boolean usegoogle)
	{
		getMendixObject().setValue(context, MemberNames.UseGoogle.toString(), usegoogle);
	}

	/**
	 * @return value of UserId_Google
	 */
	public final String getUserId_Google()
	{
		return getUserId_Google(getContext());
	}

	/**
	 * @param context
	 * @return value of UserId_Google
	 */
	public final String getUserId_Google(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.UserId_Google.toString());
	}

	/**
	 * Set value of UserId_Google
	 * @param userid_google
	 */
	public final void setUserId_Google(String userid_google)
	{
		setUserId_Google(getContext(), userid_google);
	}

	/**
	 * Set value of UserId_Google
	 * @param context
	 * @param userid_google
	 */
	public final void setUserId_Google(com.mendix.systemwideinterfaces.core.IContext context, String userid_google)
	{
		getMendixObject().setValue(context, MemberNames.UserId_Google.toString(), userid_google);
	}

	/**
	 * @return value of UseLinkedin
	 */
	public final Boolean getUseLinkedin()
	{
		return getUseLinkedin(getContext());
	}

	/**
	 * @param context
	 * @return value of UseLinkedin
	 */
	public final Boolean getUseLinkedin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.UseLinkedin.toString());
	}

	/**
	 * Set value of UseLinkedin
	 * @param uselinkedin
	 */
	public final void setUseLinkedin(Boolean uselinkedin)
	{
		setUseLinkedin(getContext(), uselinkedin);
	}

	/**
	 * Set value of UseLinkedin
	 * @param context
	 * @param uselinkedin
	 */
	public final void setUseLinkedin(com.mendix.systemwideinterfaces.core.IContext context, Boolean uselinkedin)
	{
		getMendixObject().setValue(context, MemberNames.UseLinkedin.toString(), uselinkedin);
	}

	/**
	 * @return value of UserId_Linkedin
	 */
	public final String getUserId_Linkedin()
	{
		return getUserId_Linkedin(getContext());
	}

	/**
	 * @param context
	 * @return value of UserId_Linkedin
	 */
	public final String getUserId_Linkedin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.UserId_Linkedin.toString());
	}

	/**
	 * Set value of UserId_Linkedin
	 * @param userid_linkedin
	 */
	public final void setUserId_Linkedin(String userid_linkedin)
	{
		setUserId_Linkedin(getContext(), userid_linkedin);
	}

	/**
	 * Set value of UserId_Linkedin
	 * @param context
	 * @param userid_linkedin
	 */
	public final void setUserId_Linkedin(com.mendix.systemwideinterfaces.core.IContext context, String userid_linkedin)
	{
		getMendixObject().setValue(context, MemberNames.UserId_Linkedin.toString(), userid_linkedin);
	}

	/**
	 * @return value of UseFacebook
	 */
	public final Boolean getUseFacebook()
	{
		return getUseFacebook(getContext());
	}

	/**
	 * @param context
	 * @return value of UseFacebook
	 */
	public final Boolean getUseFacebook(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.UseFacebook.toString());
	}

	/**
	 * Set value of UseFacebook
	 * @param usefacebook
	 */
	public final void setUseFacebook(Boolean usefacebook)
	{
		setUseFacebook(getContext(), usefacebook);
	}

	/**
	 * Set value of UseFacebook
	 * @param context
	 * @param usefacebook
	 */
	public final void setUseFacebook(com.mendix.systemwideinterfaces.core.IContext context, Boolean usefacebook)
	{
		getMendixObject().setValue(context, MemberNames.UseFacebook.toString(), usefacebook);
	}

	/**
	 * @return value of UserId_Facebook
	 */
	public final String getUserId_Facebook()
	{
		return getUserId_Facebook(getContext());
	}

	/**
	 * @param context
	 * @return value of UserId_Facebook
	 */
	public final String getUserId_Facebook(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.UserId_Facebook.toString());
	}

	/**
	 * Set value of UserId_Facebook
	 * @param userid_facebook
	 */
	public final void setUserId_Facebook(String userid_facebook)
	{
		setUserId_Facebook(getContext(), userid_facebook);
	}

	/**
	 * Set value of UserId_Facebook
	 * @param context
	 * @param userid_facebook
	 */
	public final void setUserId_Facebook(com.mendix.systemwideinterfaces.core.IContext context, String userid_facebook)
	{
		getMendixObject().setValue(context, MemberNames.UserId_Facebook.toString(), userid_facebook);
	}

	/**
	 * @return value of OAuthConfig_Microflows
	 */
	public final mxmodelreflection.proxies.Microflows getOAuthConfig_Microflows() throws com.mendix.core.CoreException
	{
		return getOAuthConfig_Microflows(getContext());
	}

	/**
	 * @param context
	 * @return value of OAuthConfig_Microflows
	 */
	public final mxmodelreflection.proxies.Microflows getOAuthConfig_Microflows(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.Microflows result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OAuthConfig_Microflows.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.Microflows.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OAuthConfig_Microflows
	 * @param oauthconfig_microflows
	 */
	public final void setOAuthConfig_Microflows(mxmodelreflection.proxies.Microflows oauthconfig_microflows)
	{
		setOAuthConfig_Microflows(getContext(), oauthconfig_microflows);
	}

	/**
	 * Set value of OAuthConfig_Microflows
	 * @param context
	 * @param oauthconfig_microflows
	 */
	public final void setOAuthConfig_Microflows(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.Microflows oauthconfig_microflows)
	{
		if (oauthconfig_microflows == null)
			getMendixObject().setValue(context, MemberNames.OAuthConfig_Microflows.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OAuthConfig_Microflows.toString(), oauthconfig_microflows.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return oAuthConfigMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final oauthmodule.proxies.OAuthConfig that = (oauthmodule.proxies.OAuthConfig) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "OauthModule.OAuthConfig";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
