// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oauthmodule.proxies;

public enum OAuthMessage
{
	Access(new String[][] { new String[] { "en_US", "Access" }, new String[] { "nl_NL", "Toegang" } }),
	Unauthorized(new String[][] { new String[] { "en_US", "Unauthorized" }, new String[] { "nl_NL", "Niet geauthoriseerd" } }),
	StateError(new String[][] { new String[] { "en_US", "StateError" }, new String[] { "nl_NL", "StatusFout" } }),
	XSSAttempt(new String[][] { new String[] { "en_US", "CSFRAttempt" }, new String[] { "nl_NL", "CSRF poging" } });

	private java.util.Map<String,String> captions;

	private OAuthMessage(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
